import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import BottomMenuWrapper from "@/components/menu/BottomMenuWrapper";
import SidebarWrapper from "@/components/sidebarWrapper/SidebarWrapper";
import QueryProvider from "./providers/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {children}
          <SidebarWrapper />
          <BottomMenuWrapper />
        </QueryProvider>
      </body>
    </html>
  );
}
